create table STUDENT(
ID int NOT  NULL  PRIMARY KEY,
NAME VARCHAR2(20),
AGE INT,
REGISTRATION_NUMBER VARCHAR2(20),
DEPARTMENT_ID INT
);

create table DEPARTMENT(
ID int NOT  NULL PRIMARY KEY,
NAME VARCHAR2(20),
DESCRIPTION VARCHAR2(100),
HOD VARCHAR2(20)

);


CREATE SEQUENCE hibernate_sequence
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 202700
NOCACHE
NOCYCLE;
