insert INTO STUDENT VALUES(1,'HIRAL',33,'G100',1);
insert INTO STUDENT VALUES(2,'TANYA',33,'G101',2);
insert INTO STUDENT VALUES(3,'JAINESH',31,'G102',1);
insert INTO STUDENT VALUES(4,'PARTH',34,'G103',2);

INSERT INTO DEPARTMENT VALUES (1, 'CIVIL' , 'THIS DEPARTMENT DEALS WITH CIVIL SUBJECTS', 'P. PAWAR');
INSERT INTO DEPARTMENT VALUES (2, 'MECHANICAL', 'THIS DEPARTMENT DEALS WITH MECHANICAL SUBJECTS', 'T. DESAI');

