CREATE SCHEMA IF NOT EXISTS TEST1;
CREATE SCHEMA IF NOT EXISTS TEST2;



CREATE SEQUENCE TEST1.hibernate_sequence
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 202700
NOCACHE
NOCYCLE;


CREATE SEQUENCE TEST2.hibernate_sequence
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 202700
NOCACHE
NOCYCLE;


create table TEST1.STUDENT(
ID int NOT  NULL,
NAME VARCHAR2(20),
AGE INT,
REGISTRATION_NUMBER VARCHAR2(20),
DEPARTMENT_ID INT
);

ALTER TABLE TEST1.STUDENT ADD PRIMARY KEY (ID);

create table TEST2.STUDENT(
ID int NOT  NULL,
NAME VARCHAR2(20),
AGE INT,
REGISTRATION_NUMBER VARCHAR2(20),
DEPARTMENT_ID INT
);

ALTER TABLE TEST2.STUDENT ADD PRIMARY KEY (ID);



insert INTO TEST1.STUDENT VALUES(1,'TANMAY',33,'G100',1);
insert INTO TEST1.STUDENT VALUES(2,'ANUPAM',33,'G101',2);
insert INTO TEST1.STUDENT VALUES(3,'TANVI',31,'G102',1);
insert INTO TEST1.STUDENT VALUES(4,'RICHARD',34,'G103',2);

insert INTO TEST2.STUDENT VALUES(1,'HIRAL',33,'G100',1);
insert INTO TEST2.STUDENT VALUES(2,'TANYA',33,'G101',2);
insert INTO TEST2.STUDENT VALUES(3,'JAINESH',31,'G102',1);
insert INTO TEST2.STUDENT VALUES(4,'PARTH',34,'G103',2);


create table TEST1.DEPARTMENT(
ID int NOT  NULL PRIMARY KEY,
NAME VARCHAR2(20),
DESCRIPTION VARCHAR2(100),
HOD VARCHAR2(20)

);

INSERT INTO TEST1.DEPARTMENT VALUES (1, 'ELECTRONICS' , 'THIS DEPARTMENT DEALS WITH E&C SUBJECTS', 'M. TEREDESAI');
INSERT INTO TEST1.DEPARTMENT VALUES (2, 'COMPUTERS' , 'THIS DEPARTMENT DEALS WITH CS SUBJECTS', 'M. PRABHUDESAI');

create table TEST2.DEPARTMENT(
ID int NOT  NULL PRIMARY KEY,
NAME VARCHAR2(20),
DESCRIPTION VARCHAR2(100),
HOD VARCHAR2(20)
);

INSERT INTO TEST2.DEPARTMENT VALUES (1, 'CIVIL' , 'THIS DEPARTMENT DEALS WITH CIVIL SUBJECTS', 'P. PAWAR');
INSERT INTO TEST2.DEPARTMENT VALUES (2, 'MECHANICAL', 'THIS DEPARTMENT DEALS WITH MECHANICAL SUBJECTS', 'T. DESAI');

