insert INTO STUDENT VALUES(1,'TANMAY',33,'G100',1);
insert INTO STUDENT VALUES(2,'ANUPAM',33,'G101',2);
insert INTO STUDENT VALUES(3,'TANVI',31,'G102',1);
insert INTO STUDENT VALUES(4,'RICHARD',34,'G103',2);


INSERT INTO DEPARTMENT VALUES (1, 'ELECTRONICS' , 'THIS DEPARTMENT DEALS WITH E&C SUBJECTS', 'M. TEREDESAI');
INSERT INTO DEPARTMENT VALUES (2, 'COMPUTERS' , 'THIS DEPARTMENT DEALS WITH CS SUBJECTS', 'M. PRABHUDESAI');
