
CREATE SEQUENCE hibernate_sequence
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 202700
NOCACHE
NOCYCLE;


create table STUDENT(
ID int NOT NULL PRIMARY KEY,
NAME VARCHAR2(20),
AGE INT,
REGISTRATION_NUMBER VARCHAR2(20),
DEPARTMENT_ID INT,
TENANT_ID VARCHAR2(20)
);

create table DEPARTMENT(
ID int NOT  NULL PRIMARY KEY,
NAME VARCHAR2(20),
DESCRIPTION VARCHAR2(100),
HOD VARCHAR2(20),
TENANT_ID VARCHAR2(20)
);


insert INTO STUDENT VALUES(1,'TANMAY',33,'G100',1,'TEST1');
insert INTO STUDENT VALUES(2,'ANUPAM',33,'G101',2,'TEST1');
insert INTO STUDENT VALUES(3,'TANVI',31,'G102',1,'TEST1');
insert INTO STUDENT VALUES(4,'RICHARD',34,'G103',2,'TEST1');

insert INTO STUDENT VALUES(5,'HIRAL',33,'G100',3,'TEST2');
insert INTO STUDENT VALUES(6,'TANYA',33,'G101',4,'TEST2');
insert INTO STUDENT VALUES(7,'JAINESH',31,'G102',3,'TEST2');
insert INTO STUDENT VALUES(8,'PARTH',34,'G103',4,'TEST2');




INSERT INTO DEPARTMENT VALUES (1, 'ELECTRONICS' , 'THIS DEPARTMENT DEALS WITH E&C SUBJECTS', 'M. TEREDESAI','TEST1');
INSERT INTO DEPARTMENT VALUES (2, 'COMPUTERS' , 'THIS DEPARTMENT DEALS WITH CS SUBJECTS', 'M. PRABHUDESAI','TEST1');
INSERT INTO DEPARTMENT VALUES (3, 'CIVIL' , 'THIS DEPARTMENT DEALS WITH CIVIL SUBJECTS', 'P. PAWAR','TEST2');
INSERT INTO DEPARTMENT VALUES (4, 'MECHANICAL', 'THIS DEPARTMENT DEALS WITH MECHANICAL SUBJECTS', 'T. DESAI','TEST2');

